
version: '3.8'

services:
  maven-agent:
    image: maven-agent:latest
    build:
      context: ./agents/maven

  terraform-agent:
    image: terraform-agent:latest
    build:
      context: ./agents/terraform

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-custom:latest
    container_name: jenkins-master
    user: "root" # <-- ¡¡LA LÍNEA CLAVE!!
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jcasc/jenkins.yaml:/var/jenkins_home/casc/jenkins.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc/jenkins.yaml
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
