services:
  jenkins:
    build: .
    container_name: jenkins-master
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker-dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=

  docker-agent:
    build: ./agents/docker-agent

  terraform-agent:
    build: ./agents/terraform-agent
